CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(10) DEFAULT 'EMP',
  created_at TIMESTAMP DEFAULT NOW(),
  CONSTRAINT users_role_check CHECK (role IN ('EMP', 'RM', 'APE', 'CFO'))
);
