CREATE TABLE IF NOT EXISTS reimbursements (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id),
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  amount NUMERIC(12, 2) NOT NULL,
  status VARCHAR(20) DEFAULT 'PENDING',
  rm_approved BOOLEAN DEFAULT FALSE,
  ape_approved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);
